---
- name: Pre-create Domain
  hosts: windows
  gather_facts: true
  tasks:
    - name: Create new domain in a new forest on the target host and reboot
      microsoft.ad.domain:
        dns_domain_name: ansible.vagrant
        safe_mode_password: password123!
        reboot: true

- name: Begin Hardening CIS 2
  hosts: windows
  gather_facts: true
  roles:
    - role: cis_harden
