---

# The CIS Control wants IPv6 disabled if not in use.
# We are using the rhel8cis_ipv6_required to specify if you have IPv6 in use
- name: "3.1.1 | PATCH | Verify if IPv6 is enabled on the system"
  block:
      - name: "3.1.1 | PATCH | Verify if IPv6 is enabled on the system |disable all except localhost"
        ansible.posix.sysctl:
            name: "{{ item }}"
            value: '1'
            sysctl_set: true
            state: present
            reload: true
            sysctl_file: "{{ rhel8cis_sysctl_file }}"
        with_items:
            - net.ipv6.conf.all.disable_ipv6
            - net.ipv6.conf.default.disable_ipv6
            - net.ipv6.conf.lo.disable_ipv6

      - name: "3.1.1 | PATCH | Verify if IPv6 is enabled on the system | disable localhost sysctl"
        ansible.posix.sysctl:
            name: net.ipv6.conf.lo.disable_ipv6
            value: '1'
            sysctl_set: true
            state: present
            reload: true
            sysctl_file: "{{ rhel8cis_sysctl_file }}"
        notify: change_requires_reboot
        when:
            - rhel8cis_ipv6_disable_localhost

      - name: "3.1.1 | PATCH | Verify if IPv6 is enabled on the system | disable localhost /etc/hosts"
        ansible.builtin.lineinfile:
            path: /etc/hosts
            regexp: '^(::1.*)'
            line: '#\1'
            backrefs: true
        notify: change_requires_reboot
        when:
            - rhel8cis_ipv6_disable_localhost

  when:
      - not rhel8cis_ipv6_required
      - rhel8cis_rule_3_1_1
  tags:
      - level1-server
      - level1-workstation
      - manual
      - patch
      - ipv6
      - networking
      - rule_3.1.1

- name: "3.1.2 | PATCH | Ensure SCTP is disabled"
  block:
      - name: "3.1.2 | PATCH | Ensure SCTP is disabled | CIS"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install sctp(\\s|$)"
            line: "install sctp /bin/true"
            create: true
            mode: 0600

      - name: "3.1.2 | PATCH | Ensure SCTP is disabled | blacklist"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/blacklist.conf
            regexp: "^(#)?blacklist sctp(\\s|$)"
            line: "blacklist sctp"
            create: true
            mode: 0600
  when:
      - rhel8cis_rule_3_1_2
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - sctp
      - rule_3.1.2

- name: "3.1.3 | PATCH | Ensure DCCP is disabled"
  block:
      - name: "3.1.3 | PATCH | Ensure DCCP is disabled | CIS"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install dccp(\\s|$)"
            line: "install dccp /bin/true"
            create: true
            mode: 0600

      - name: "3.1.3 | PATCH | Ensure DCCP is disabled | blacklist"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?blacklist dccp(\\s|$)"
            line: "blacklist dccp"
            create: true
            mode: 0600
  when:
      - rhel8cis_rule_3_1_3
  tags:
      - level2-server
      - level2-workstation
      - automated
      - dccp
      - patch
      - rule_3.1.3

- name: "3.1.4 | PATCH | Ensure wireless interfaces are disabled"
  block:
      - name: "3.1.4 | AUDIT | Ensure wireless interfaces are disabled | Check if nmcli command is available"
        ansible.builtin.shell: rpm -q NetworkManager
        changed_when: false
        failed_when: false
        check_mode: false
        register: rhel_08_nmcli_available

      - name: "3.1.4 | AUDIT | Ensure wireless interfaces are disabled | Check if wifi is enabled"
        ansible.builtin.shell: nmcli radio wifi
        register: rhel_08_wifi_enabled
        changed_when: rhel_08_wifi_enabled.stdout != "disabled"
        failed_when: false
        when: rhel_08_nmcli_available.rc == 0

      - name: "3.1.4 | PATCH | Ensure wireless interfaces are disabled | Disable wifi if enabled"
        ansible.builtin.shell: nmcli radio all off
        changed_when: false
        failed_when: false
        when: rhel_08_wifi_enabled is changed
  when:
      - rhel8cis_rule_3_1_4
  tags:
      - level1-server
      - automated
      - patch
      - wireless
      - rule_3.1.4
