---

- name: "4.2.3 | PATCH | Ensure permissions on all logfiles are configured"
  ansible.builtin.shell: find /var/log -type f -exec chmod g-wx,o-rwx "{}" +
  failed_when: false
  when:
      - rhel8cis_rule_4_2_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - logfiles
      - rule_4.2.3
